apiVersion: v1
kind: PersistentVolume
metadata:
  name: bindu-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/Bindu_PV_dir" 
